# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Homelab India
site_description: Official Homelab India Wiki
site_url: https://wiki.homelabindia.org
repo_url: https://github.com/homelabindia/wiki
repo_name: homelabindia/wiki
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/header-search.js
markdown_extensions:
  - attr_list
  - md_in_html
  - markdown_captions
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - glightbox
  - search
  - social
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  custom_dir: overrides
  logo: assets/brand/homelab-india-mark.svg
  favicon: assets/brand/homelab-india-mark.svg
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

nav:
  - Home: index.md
  - Hardware:
      - Mini PCs: hardware/minipc.md
      - Routers: hardware/routers.md
      - Switches: hardware/switches.md
      - HDDs: hardware/hdd.md
      - SSDs: hardware/ssd.md
      - VPS: hardware/vps.md
  - Software:
      - Operating System: software/operating-system.md
      - RAID and Filesystems: software/raid.md
      - Networking:
          - Exposing Homelab: software/networking/exposing.md
          - Multiple IPv6 Prefixes: software/networking/multiple-ipv6-prefixes.md
          - Speedtest: software/networking/speedtest.md
  - Community:
      - Indian Homelab YouTubers: community-guides/youtubers.md
  - Blog: blog/index.md
